name: m9
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  permission_handler: ^12.0.0+1
  geolocator: ^13.0.3
  get_it: ^8.0.3
  smooth_page_indicator: ^1.2.1
  carousel_slider: ^5.0.0
  provider: ^6.1.5
  http: ^1.4.0
  shared_preferences: ^2.5.3
  cached_network_image: ^3.4.1
  flutter_svg: ^2.1.0
  intl: ^0.20.2
  flutter_localization: ^0.3.2
  flutter_bloc: ^9.1.1
  connectivity_plus: ^6.1.4
  dartz: ^0.10.1
  equatable: ^2.0.7
  dio: ^5.8.0+1
  mapbox_maps_flutter: ^2.8.0
  location: ^8.0.0
  flutter_dotenv: ^5.2.1
  map_location_picker: ^1.3.4
  google_maps_flutter: ^2.12.2
  nav_service: ^0.1.0
  flutter_polyline_points: ^2.1.0
  lucide_icons_flutter: ^3.0.3
  animated_rating_stars: ^1.0.1
  webview_flutter: ^4.13.0
  path_provider: ^2.1.5
  hive_ce: ^2.11.3
  hive_ce_flutter: ^2.3.1
  easy_localization: ^3.0.7+1
  encrypt: ^5.0.3
  pinput: ^5.0.1

  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/splash_images/
    - assets/images/drivermode/
    - assets/images/usermode/
    - assets/icons/
    - assets/fonts/
    - assets/.env

  fonts:
      - family: NotoSansLao
        fonts:
          - asset: assets/fonts/NotoSansLao.ttf